log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database: "auth_test"
  ssl_mode: "disable"

kratos:
  base_url: https://flamboyant-goldwasser-wpzu88jwpx.projects.oryapis.com/api/kratos/public
  cookie: ory_session_flamboyantgoldwasserwpzu88jwpx

event_api:
  enabled: true
  host: "127.0.0.1"
  port: 4222
